version: '3.8'

services:
  back_base_arq:
    build:
      context: ./back_base_arq
    ports:
      - "3030:3030"
    environment:
      DATABASE_HOST: postgresql
      DATABASE_USER: enmarcm
      DATABASE_PASSWORD: 1234
      DATABASE_NAME: postgredb

  front_arq:
    build:
      context: ./front-arq
    ports:
      - "5174:5174" 

  postgresql:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: enmarcm
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgredb
    ports:
      - "5432:5432"